#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bash .config/bspwm/monitors.sh
bspc config border_width        2
bspc config window_gap         	7 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


compton --config ~/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
${HOME}/.fehbg
/usr/lib/xfce4/notifyd/xfce4-notifyd &
MONITOR="DP-0" polybar -c /home/pietro/.config/polybar/config bar &
#bash $HOME/.config/polybar/launch.sh --forest >> ~/.config/bspwm/logs/polybar.logs


# SHIT YOU SHOULD REMOVE ON YOUR CONFIGURATION

xinput --set-prop 9 'libinput Accel Speed' -0.7
xset m 1 1
$HOME/scripts/bomdiameninas.sh & disown
sleep 3
#MONITOR="HDMI-0" polybar -q main  "--config=/home/pietro/.config/polybar/forest/config.ini" &
MONITOR="HDMI-0" polybar -c /home/pietro/.config/polybar/config_monitor_2 sidebar &
